### ISSUE TITLE
gradle rewriteRun

### ISSUE THREAD

**Issue by nagkumar** [moderneinc/rewrite-recipe-starter#27]
rewrite-recipe-starter>gradle rewriteRun

```
> Configure project :
Inferred project: rewrite-recipe-starter, version: 0.1.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
Task 'rewriteRun' not found in root project 'rewrite-recipe-starter'.

* Try:
> Run gradle tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
```

**Comment by SimonVerhoeven** [comment]
This project is for writing your own recipes, if you want to run `rewriteRun` make sure you have the `org.openrewrite.rewrite` in your build file.

**Comment by nagkumar** [comment]
Thank You, I am running this build file https://github.com/moderneinc/rewrite-recipe-starter/blob/main/build.gradle.kts

Are u saying this file patching.. to make the build work?

**Comment by SimonVerhoeven** [comment]
No, this project is meant as a baseline for writing your own recipe. So if you're happy with the recipe you've written, you'd then publish it to your local repository to test it, add it to the project you want to apply the recipe to, and on that one perform rewriteRun. See for reference: https://docs.openrewrite.org/authoring-recipes/recipe-development-environment

**Comment by timtebeek** [comment]
Indeed; this project is intended to allow you to create your own recipe library; it's not intended to run OpenRewrite recipes on this project itself. I feel like the README adequately explains that, but if you have any suggestions for improvement do please let us know! 

I'm closing the issue for now and strike it up to temporary confusion; hope you agree that this has been cleared up. :)
