### ISSUE TITLE
documentation update, gradle publishToMavenLocal not working

### ISSUE THREAD

**Issue by nagkumar** [moderneinc/rewrite-recipe-starter#30]
readme.md can have commands that are needed to be used to publish on local maven repo instead of public moderne repo..

i.e. wish to know how to build, manage and reuse recipes within an enterprise, be told as this is part of custom recipe development.

**Comment by nagkumar** [comment]
```
> gradle publishToMavenLocal

> Configure project :
Git repository not found at  recipe-starter -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a different directory.

> Task :signNebulaPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signNebulaPublication'.
> Cannot perform signing task ':signNebulaPublication' because it has no configured signatory

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 20s
10 actionable tasks: 2 executed, 8 up-to-date

```

**Comment by timtebeek** [comment]
What kind of changes have you made to the rewrite-recipe-starter locally? Because if I do a fresh clone and run `./gradlew publishToMavenLocal` here that works; might there be local changes similar to [your earlier issue](https://github.com/moderneinc/rewrite-recipe-starter/issues/29#issuecomment-1755882140) that are tripping you up?

**Comment by nagkumar** [comment]
Thx Tim, I took this repo as is  and trying on windows, did install gpg for windows https://files.gpg4win.org/gpg4win-4.2.0.exe

Is there any configuration such as my local user and password that is needed for signing to get through gradle?

**Comment by nagkumar** [comment]
https://github.com/moderneinc/rewrite-recipe-starter/issues/29#issuecomment-1776470110

**Comment by timtebeek** [comment]
I've made the command to install to the local Maven repository runnable from your IDE, if you open the README there.
https://github.com/moderneinc/rewrite-recipe-starter/commit/705533161166367783ecbacc502e5417fbd2ec40
Hope that helps!
