### ISSUE TITLE
[Bug] Workflow receive-pr fails - `Task 'licenseFormat' not found`

### ISSUE THREAD

**Issue by timo-a** [moderneinc/rewrite-recipe-starter#54]
I have forked this repository and created a PR on my fork, but the job `upload-patch` in the workflow `receive-pr` 
https://github.com/timo-a/rewrite-recipe-starter/actions/runs/9051981890/job/24869151089?pr=1
fails:
> Task 'licenseFormat' not found in root project 'rewrite-recipe-starter'.

I could not spot any such task in https://github.com/openrewrite/rewrite-migrate-java/blob/main/build.gradle.kts but that repo has a `LICENSE` file whereas this repo doesn't. ~Maybe that's the issue?~ Just tried it on my fork, adding such  a file alone is not the solution.

I inadvertently created the same PR against this repo as well: https://github.com/moderneinc/rewrite-recipe-starter/pull/53.
If the workflow is approved there I expect the same error. Maybe that helps in the investigation, otherwise the PR can be closed.

**Comment by timtebeek** [comment]
Thanks for pointing this out! We recently reshuffled how this project uses our shared build plugins, to make it easier to adopt for folks in more restrictive environments (https://github.com/openrewrite/rewrite-build-gradle-plugin/commit/7f0b11d93bf3eb0ebc4e300f41a4180584789c71 & https://github.com/moderneinc/rewrite-recipe-starter/commit/15bdd28cfa504d275c528e8e56c43fa196599aff). As part of that I guess the licenseFormat plugin was dropped, but the workflow wasn't updated. I've fixed that now in https://github.com/moderneinc/rewrite-recipe-starter/commit/97d48acdf5497eec26a39fab0f362d77e27b3060, thanks to your help. :)
