### ISSUE TITLE
StringIsEmpty with Refaster test fails

### ISSUE THREAD

**Issue by Uriziel47** [moderneinc/rewrite-recipe-starter#66]
Good Morning,

I just wanted to get started on openrewrite. So I decided to check this Repository first and _get my hands dirty_. 
Unfortunately I got stucked in the first try using _Refaster_. 

So after writing the _Refaster_ recipe of `StringIsEmpty`. I didn't get the testcase, `StringIsEmpty::standardizeStringIsEmpty` to pass. Either the case of `string.equals("")` or `string.length == 0` case is wrong. 

So after inspecting the generated class. I realized, that the first `@BeforeTemplate` annotation decides which visitor method will be used for all `@BeforeTemplate` annotated methods.

In case `string.equals("")` the visitor method `visitMethodInvocation` is been used. And in case of `string.length == 0` the visitor method `visitBinary` is been used.

So I am just curious, if I misunderstood the [documentation](https://docs.openrewrite.org/authoring-recipes/refaster-recipes),  used the wrong version, or is this a bug, which I did not find in the _issues_.

For clarification I created a branch in my learning repository:  [link to repo](https://github.com/Uriziel47/learning-openrewrite/tree/issues/refaster_bug).
In there the discussed variants with the testcases.

- StringIsEmptyCheckEqualsFirst
- StringIsEmptyCheckLengthFirst
- StringIsEmptyWithSubclasses (splitted `equals` and `length` into refaster subclasses)
- StringisEmptyVisitorRecipe (The recipe I thought it would be generated)

Thanks for your answers in advance.

**Comment by timtebeek** [comment]
Hi @Uriziel47 ; thanks for the detailed report! This is indeed a bug, that we'll track against the refaster template processor:
- https://github.com/openrewrite/rewrite-templating/pull/117

Let's continue the conversation there! Any fix & release would also resolve that issue here, without a need for changes in this project beyond bumping the version.

**Comment by Uriziel47** [comment]
Hi @timtebeek, thank you very much for the fast feedback and fix!

**Comment by timtebeek** [comment]
You're welcome; your report made it easy to pick up. You'll have noticed I also released a new version of rewrite-templating and bumped the versions here. We'll do a full new release this Wednesday. Thanks again!
